### ISSUE TITLE
GUI Consistency Question

### ISSUE THREAD

**Issue by Mystara0001** [Soartex-Modded/Modded-1.7.x#104]
I've noticed that quite a few of the GUI images are using the wooden textures, yet some are using the gray "stone" texture. Still some use other pretty fancy versions to reflect the machine they are used on. The attached images are merely examples of each type of GUI mentioned here.

![scrapboxrecipes](https://cloud.githubusercontent.com/assets/6118189/8294208/b5e73bf6-18ef-11e5-856e-126560f81184.png)
![guibottler](https://cloud.githubusercontent.com/assets/6118189/8294215/bd5c2e28-18ef-11e5-9b35-f47b866489de.png)
![gui_focuspouch](https://cloud.githubusercontent.com/assets/6118189/8294276/2b3b4a50-18f0-11e5-8b2d-409e437fab5b.png)

Is there a specific reason to use one over the other?

**Comment by artdude543** [comment]
We generally use the metal ones for main machine mods, and the wooden for the rest. In TC cases we use our inventory texture and the TC top textures. (As a placeholder till we make the main texture)
