### ISSUE TITLE
IC2 Experimental Miner GUI is wrong

### ISSUE THREAD

**Issue by Sekra** [Soartex-Modded/Modded-1.7.x#106]
I understand this is a bit of a tricky fix because IC2 and IC2 Exp share all the same files and resources, but they've radically changed the GUI of the Miner in IC2 Exp and thus the one in this pack does not work at all with the current version. I would suggest either deleting the file alltogether so each version of the mod will use the non-HD version of the GUI or you are free to use this HD version that I made to replace the broken GUI (which will of course break the GUI for anyone not using IC2 Exp):

![guiminer](https://cloud.githubusercontent.com/assets/5526248/8628809/8f7fc262-275e-11e5-92bb-e7978aa89243.png)

**Comment by QORTEC** [comment]
Please correct me if I'm wrong, but the last non-"experimental" version of IC² was for MC 1.5.x. 
Assuming that only experimental versions of IC² are available for 1.7.10 and that modpacks are keeping the mod up to date, the GUI should be updated.

Do you know when this change was made and if there any other outdated IC² GUI's.

**Comment by Sekra** [comment]
It's been around for a while now, took us a while to figure out the problem was the GUI instead of a bug since it will allow you to place items in the outdated GUI slots. I can't think of any other ones that are blatantly "wrong" like this, but there is a whole bunch that are missing updated GUI's.. 

And yeah.. true about the version stuff..

**Comment by QORTEC** [comment]
I am planing to do some GUI updates for Mekanism, so probably should also look at IC² while I'm at it.
Assuming that the GUIs are relatively simple I shouldn't have any issues updating IC².

At first look it seams like the majority of textures are "up to date" and 33 new textures will need to be added.
If you have updated any other GUIs I would like to use those as well, I will try to start working on this "soon".
