### ISSUE TITLE
Chisel lavastone

### ISSUE THREAD

**Issue by AeroyrHwrdd** [Soartex-Modded/Modded-1.7.x#113]
There is lavastone in 1.6 modded repo and I have been using them for my 1.7 textures personally and they work fine (unlike the aqua textures but that's not Soartex team's fault, that's something for the modder to implement) https://github.com/Soartex-Modded/Modded-1.6.x/tree/master/Chisel/assets/chisel/textures/blocks/lavastone. I've been wondering why they haven't been ported into the 1.7 repo.

**Comment by artdude543** [comment]
Thanks for bringing this up, the textures have been ported over now :) Commit: https://github.com/Soartex-Modded/Modded-1.7.x/commit/3fed636147d42eb821e82978e743f767be257515

**Comment by AeroyrHwrdd** [comment]
No problem. I'm assuming it was just forgotten but there could have been a reason it had not been ported (crashes, errors that other people had experienced)
