### ISSUE TITLE
Chisel - Auto Chisel Bug

### ISSUE THREAD

**Issue by alfw** [Soartex-Modded/Modded-1.7.x#118]
GUI broken

Slots for upgrade slots are off + missing the last upgrade slot.

https://files.alfw.tv/1451491403-Alf-2148.png

**Comment by zISKo666** [comment]
fixed with commit https://github.com/Soartex-Modded/Modded-1.7.x/commit/297b39bcdbbd37e52671dca778edc644bfa26b36
