### ISSUE TITLE
[Request] OpenComputers MC 1.7.10

### ISSUE THREAD

**Issue by XFactHD** [Soartex-Modded/Modded-1.7.x#120]
As I am unable to create an account on the Soartex forum, I am posting this suggestion here: It would be awesome if you could add textures for the OpenComputers mod for 1.7.10 (and eventually also for 1.8).
Website: oc.cil.li

**Comment by justin0a0** [comment]
I had started a bunch of these a while ago and never got around to finishing them. I'll see what I can get done here in the next week or so and post the results of it.

**Comment by XFactHD** [comment]
That's great.
