### ISSUE TITLE
[Pneumaticcraft] Plastic Mixer GUI

### ISSUE THREAD

**Issue by XFactHD** [Soartex-Modded/Modded-1.7.x#121]
Some slots in the GUI of the Plastic Mixer are placed wrong.
![2016-01-09_19 57 57](https://cloud.githubusercontent.com/assets/11262040/12217796/a5a20fea-b70b-11e5-9d2a-53c4ac3ca053.png)

**Comment by artdude543** [comment]
Will fix

**Comment by zISKo666** [comment]
ready in a few minutes ;)

**Comment by zISKo666** [comment]
fixed with commit https://github.com/Soartex-Modded/Modded-1.7.x/commit/d2199b2c19231ddc5d7dee28f91a5ed0d7cafc03

**Comment by XFactHD** [comment]
Awesome, thanks!
