### ISSUE TITLE
Harder Ores - Need to figure out "15" steps

### ISSUE THREAD

**Issue by devanchya** [Soartex-Modded/Modded-1.7.x#126]
There's a mod that's not very popular called Harder Ores.  It basically lets you break an ore block up to 15 times depending on "density" and the ore chunks are smelted so that 1 chunk = 2 tiny dust, 8 tiny dust = 1 dust.

The problem I'm having is the Ore needs a way to show 15 changed states.  I can't get the cracks to work right or the blocks to look soartex.  Anyone able to help?

Example of what I've done:
 State 15 is orignal ore
State 12 example:
![gold_ore_12](https://cloud.githubusercontent.com/assets/6947885/12799508/234a2442-ca9d-11e5-8ca0-d08675559668.png)
State 10 example:
![gold_ore_10](https://cloud.githubusercontent.com/assets/6947885/12799521/37b5085c-ca9d-11e5-9cbd-7f27504a89ce.png)
State 5 example:
![gold_ore_5](https://cloud.githubusercontent.com/assets/6947885/12799524/3d8faea8-ca9d-11e5-9349-cd022aca6708.png)
State 1 example:
![gold_ore_0](https://cloud.githubusercontent.com/assets/6947885/12799538/4b7e5f96-ca9d-11e5-9033-9951af1e5b7b.png)

**Comment by goldbattle** [comment]
You have a good start here. For overlaying your cracks, you will want to use the blockstates in the vanilla pack. You can apply these overtop your base textures and go from there. Overlay them using the "grain merge". More info on that [here](http://clownfishcafe.blogspot.com/2013/12/gimp-layer-modes-grain-extract-to-value.html#gmerge)

![destroy_stage_5](https://cloud.githubusercontent.com/assets/2222562/12801506/27a076be-caab-11e5-8406-f48ec6d7c3fc.png) + ![4b7e5f96-ca9d-11e5-9033-9951af1e5b7b](https://cloud.githubusercontent.com/assets/2222562/12801484/0901ce1a-caab-11e5-8158-54f6922ac629.png) = ![example](https://cloud.githubusercontent.com/assets/2222562/12801488/0e2e0b92-caab-11e5-8f97-6f352d05ad43.png)
