### ISSUE TITLE
Can't make parts from other mods

### ISSUE THREAD

**Issue by merdinarchfire** [Soartex-Modded/Modded-1.7.x#127]
this is the version i am using ExtraTiC-1.7.10-1.4.5 
TConstruct-1.7.10-1.8.8
IguanaTinkerTweaks-1.7.10-2.1.5

I have a modpack set up that has natura-1.7.10-2.2.0.1, Botania r1.8-248, and Thaumcraft-1.7.10-4.2.3.5. but for some reason i can't make anything using firey string, thaumic ingot, or manasteel. Has anyone else seen this problem? i tried looking and couldn't find anything about it.

**Comment by artdude543** [comment]
This is not texture related. This repo is for modded textures for Soartex. Not mod support please find the mod support thread / repo for help with the mod.
