### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by THEVOLCO** [Soartex-Modded/Modded-1.7.x#134]
Hi,
When I launch the game I get following crash report:
http://pastebin.com/8Wr5NAvZ
Can you help me pls?

**Comment by xCausxn** [comment]
Try asking the mod creator of watercraft, as that is where the issue is. So this is not a soartex issue :)

**Comment by artdude543** [comment]
For starters this is a repo for reporting issues with Soartex (The texture pack) not for mod crashes. The  mod "watercraft" is causing the crash. Please find the correct reporting system for the mod; and kindly please don't post mod crashes here please unless it's actually an issue with the texture pack.

**Comment by THEVOLCO** [comment]
ok sry and thx :)
