### ISSUE TITLE
AE2's ME Interface GUI is incorrect

### ISSUE THREAD

**Issue by sdayton** [Soartex-Modded/Modded-1.7.x#135]
The current GUI for the ME Interface ( /Applied_Energistics_2/assets/appliedenergistics2/textures/guis/interface.png ) in Applied Energistics 2 is invalid since it only has 8 slots at the top and the mod has 9.  Attached is an updated file that adds the missing 9th slot.
![interface](https://cloud.githubusercontent.com/assets/29515/15609440/0f069740-23ee-11e6-979b-2c629c9ce5ed.png)

**Comment by artdude543** [comment]
Ahh I see. thanks for the fixed texture! Will add it to the repo in a bit :)
