### ISSUE TITLE
Will you continue update Witchery on 1.10.2?

### ISSUE THREAD

**Issue by BurovB** [Soartex-Modded/Modded-1.7.x#152]
I think that 1.10.2 is very interesting version for magic mods because updates Blood Magic, Botania, Ars Magica and in future maybe Thaumcraft will be exciting. Witchery is much interesting than all this mods but it was abandoned. Will you continue update Witchery on 1.10.2?

**Comment by AeroyrHwrdd** [comment]
@BurovB I have been slowly working on the items for Witchery. My original focus was on 1.7 as not all of those are done. But peeps on my server have been requesting Ztones textures and Big Doors textures and Blocks are a bit of a slog for me.I also ran out of creative ideas for textures. Btw if you have any ideas, glad of the help.
