### ISSUE TITLE
your mod in 1.10.2 ?

### ISSUE THREAD

**Issue by fflortix** [Soartex-Modded/Modded-1.7.x#153]
You can update your mod in 1.10.2 please ? If you have this project sorry for the issue :D

**Comment by mgdgfbhevdyeh** [comment]
https://github.com/Soartex-Modded/Modded-1.10.x

**Comment by thespellslinger** [comment]
I like to know so I can have a go at it in 1.10.2 and onwards. it would be very much appreciated if you do that. I intend to  get it through Curse
PS; Keep up the good work with this mod.

**Comment by popwebz** [comment]
This texture pack already supports 1.10.2. Closing issue
