### ISSUE TITLE
Tinkers 1.8.0 Update

### ISSUE THREAD

**Issue by goldbattle** [Soartex-Modded/Modded-1.7.x#59]
Seems there is a beta out for tinkers. I am not sure if the update has back compatable textures, but if it does it would be preferred to update to it. Some screenshot below are provided by @alfw. Key things broken are the tool station and patterns, and some new tool content added. Also see https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/41 for some more content.

![2014-12-28_902-419-28-05-23-51](https://cloud.githubusercontent.com/assets/2222562/5563042/bfee8006-8e1f-11e4-8663-70a15571c6dd.png)
![2014-12-28_1008-516-28-05-22-46](https://cloud.githubusercontent.com/assets/2222562/5563046/d34327c4-8e1f-11e4-8e11-d42dc1b17d8c.png)

/cc @Soartex-Modded/contributors

**Comment by KindarConrath** [comment]
Arrows render differently in the bows now too.  The current arrows show up as two arrows crossed in the bow.

**Comment by artdude543** [comment]
We are aware of problems with the current textures and the new ones. We are going to aim for a fix in the next few weeks.

**Comment by artdude543** [comment]
Okay well in fact I've found the issue and it's not that hard to fix, so expect a fix soon rather than later.
