### ISSUE TITLE
Gregtech 5.07 intruduced many changes in meta material icons

### ISSUE THREAD

**Issue by leagris** [Soartex-Modded/Modded-1.7.x#65]
Is someone (@Alheimerjung maybe?) working on new meta-materials icons?

New folders:
- [x] /assets/gregtech/textures/blocks/materialicons
- [x] /assets/gregtech/textures/items/materialicons

Some old icon files can be moved/renamed and duplicated as-is
Some materials could benefit specific new icons

[Relevant Changelog for GregTech 5.07](http://files.minecraftforge.net/maven/com/gregoriust/gregtech/changelog.txt):
> [ADDED] A TextureSet for Magnetic Items with a Plus/Minus Overlay.
> [ADDED] A few new Meta Items, such as small Gears (1 Unit), Springs (1 Unit), small Springs (1/4 Unit), the Rotors (as the 5 already known ones, but now as MetaItem, the old 5 ones will get unificated into the OreDicted ones) and Long Sticks (1 Unit, is basically 2 Sticks).
> [ADDED] A few Batch Files inside the Assets Folders to copy any drag-dropped single File into a selection of Texture Sets at once.
> [API] Some Texture Set related improvements for the MetaGenerated Items. Both the Location of the Files and the Texture Set Code itself have changed. Every Icon of the particular Texture Set can be changed for Texturepack Reasons.
> [API] OreDict Prefixes can now be assigned a TextureSet Array Index in order to have Icons. Since the TextureSet is Array based it is only useful for me, but it is something.

**Comment by Alheimerjung** [comment]
Yes, but is very much stuff. It will take some time.

**Comment by leagris** [comment]
Ok, then I am working on moving, adapting blocks/materialicons.
Would you like to do items/materialicons?

I assigned this issue to me, and will keep open to track all related changes.

**Comment by leagris** [comment]
Committed 442e6a0a2997ad3f2c99e4c163e3211397e6b86b
[fix] Part of issue #65
These are translated and adapted from previous Gregtech textures.
Be it a Groundwork:
Feel free to work and submit more specific variations.

**Comment by artdude543** [comment]
Make sure with commits being pushed with the fixes that the mod.json gets updated with the version supported.

**Comment by leagris** [comment]
It was already at 5.07 despite here-about issue.

**Comment by Alheimerjung** [comment]
https://github.com/Soartex-Modded/Modded-1.7.x/pull/67

**Comment by leagris** [comment]
Great job, thank you for your contrib.

There may still exist untextured meta like smallgear, though I consider issue handled for the most part.

Hope it can stick to next upcoming Gregtech 6 without too many incompatible changes.
