### ISSUE TITLE
Mob spawning issue

### ISSUE THREAD

**Issue by CrowAU** [Soartex-Modded/Modded-1.7.x#66]
Witchery messes with mobs from ars magica and gravestone mod causing them to spawn in dimensions they shouldn't be such as twilight.

**Comment by Mierzen** [comment]
@CrowAU are you sure you meant to post this in the Soartex repo?
Since Soartex Fanver is only a bunch of textures, it is not possible that Soartex can cause mobs to spawn where they shouldn't...

**Comment by alfw** [comment]
@CrowAU this is a issues area for Soartex textures and not problems with the mod's itself! 

For witchery you want to go to http://minecraft.curseforge.com/mc-mods/69673-witchery
Ars magica devs sort of quited modding, probly wont get much support from ther but here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292222-ars-magica-2-version-1-4-0-008-updated-february-6
And for the gravestone mod you want to go to: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288082-gravestone-mod-v2-11-3

- Alf

**Comment by CrowAU** [comment]
Oh man sorry, how embarrassing.

**Comment by alfw** [comment]
@CrowAU no problems! it happens  ;)

Atlast that shuld point you to the way where to report it :)
