### ISSUE TITLE
Jabba

### ISSUE THREAD

**Issue by KindarConrath** [Soartex-Modded/Modded-1.7.x#73]
Just noticed that when Jabba barrels have a label on the top, or are facing upwards, they have a transparent border on them, happens on ALL upgraded barrels but not on the base barrel.

Left is not upgraded, right is with first upgrade.

Normal Texture:
Front:
![2015-03-06_12 50 59](https://cloud.githubusercontent.com/assets/5119861/6530779/d9bf0876-c401-11e4-851d-a356e85dad0a.png)

Top:
![2015-03-06_12 51 03](https://cloud.githubusercontent.com/assets/5119861/6530780/d9c0c530-c401-11e4-9361-ca261c94f388.png)

x64 Texture
Front:
![2015-03-06_13 03 04](https://cloud.githubusercontent.com/assets/5119861/6530812/0c3fd17c-c402-11e4-83c5-a133fc6c1708.png)

Top:
![2015-03-06_13 03 10](https://cloud.githubusercontent.com/assets/5119861/6530782/d9c9a5ec-c401-11e4-8b35-c0920f13271e.png)

**Comment by artdude543** [comment]
Will push a fix for this soon! Thanks for bringing this to our attention.

**Comment by Mystara0001** [comment]
I have created a fix for this bug. Would you like me to push it?

![barrel_top_label](https://cloud.githubusercontent.com/assets/6118189/7105131/c09b8d8c-e0bd-11e4-9a78-e1a187dd18da.png)

**Comment by zISKo666** [comment]
Checked it in game and it is looking good to me. So it is ok to push, I think!

**Comment by goldbattle** [comment]
Commit dat :+1:
