### ISSUE TITLE
[EnderIO] New EnderIO layouts for Farm GUI, and widgets in newer dev builds

### ISSUE THREAD

**Issue by zeryl** [Soartex-Modded/Modded-1.7.x#74]
I'm not sure the best way to handle since EnderIO has changed items in their dev builds, but widgets.png is now widgetsv2.png, and at least the farm gui has changed.

Widgets: https://github.com/SleepyTrousers/EnderIO/commit/a88c7e8ea12109cb861420b4d46f85784214e687

Farm GUI: 
https://github.com/SleepyTrousers/EnderIO/commit/a79ae8b0d3075a32ba53795cccb30ec1f82ccb6b

Those are the two I've found so far.  I'm sure others exist, as there is quite a bit of work going on. I also completely understand if this won't get touched until a beta/prod build is done of EnderIO, as I'm not sure how best it could even be implemented.

**Comment by zISKo666** [comment]
I'll look into this when it is available on curseforge.

**Comment by goldbattle** [comment]
I think @artdude543 pushed some textures the other day, might have fixed some of these. I don't think these textures are live in the downloads.

https://github.com/Soartex-Modded/Modded-1.7.x/commit/82930c193337affa98c423ee99a3faa4adbe895b

**Comment by artdude543** [comment]
The changes are already in the CurseForge download, I did double check the fix myself. As for the changes they are making, I have kept my eye on it and talking with the devs to ensure nothing major is being changed to break compatibility.

**Comment by zISKo666** [comment]
okies, well then there's nothing to do for me ;)
