### ISSUE TITLE
Using 1.6.x Assets in 1.7.x

### ISSUE THREAD

**Issue by Mystara0001** [Soartex-Modded/Modded-1.7.x#80]
Is there a rule on using assets from previous versions?
I'm asking specifically because I noticed that there isn't an ExtrabiomesXL in 1.7.x but there is in 1.6.x. The textures seem to match in the updated version of the mod. Can it just be copied over with the existing textures and then built on from there?

**Comment by goldbattle** [comment]
That is exactly what we want people to do! No need to remake already good textures. Now if you go through them, after matching them up with the new version, and find a texture that should probably be of higher quality, I would probably remake it, or not include it.

Hope this answers your question. Make sure you check out *all* the modded repositories.
