### ISSUE TITLE
Any other plans on Vampires and "Direwolfs" ? 

### ISSUE THREAD

**Issue by Eneitilyn** [Soartex-Modded/Modded-1.7.x#94]
I have suggestions like maybe "Daylight rings ?" protecting you from daylight death mostly.. it's an idea from Vampire Diaries...also comparing them to each other i think Vampires have kinda more harsh cons than Werewolfs...diying instantly ? there could be some kind of item or structure which negates that maybe something like a ritual or powered thing which creates "mist,fog" ?

**Comment by leagris** [comment]
Wrong project
