### ISSUE TITLE
BiblioCraft - Oak Case

### ISSUE THREAD

**Issue by alfw** [Soartex-Modded/Modded-1.7.x#96]
Oak case ( might be other to) missing one row of px.

https://files.alfw.tv/1431897438-Alf-623.png

**Comment by justin0a0** [comment]
if nobody else gets to it in the next day or two ill peek at it.
It's at the bottom of my list AS 2 doesnt have it ;)

**Comment by zISKo666** [comment]
I've tried to fix it. Unfortunately there's nothing I can do because it is in the mods code and have to be fixed by the mod author.
The mod calculates the textures by using the vanilla (textured) blocks.
You can check it, by removing the textures (bibliocraft/models) from your resource pack.

**Comment by artdude543** [comment]
Yeah I looked into this and found the offending code, I've sent a message to the mod developer to see if anything can be tweaked. But going to close this for now as it's something we can't fix with our textures.
